# Site wide configuration

title: Umang Bhatt         
locale: en_US
url: https://umangsbhatt.github.io
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Umang Bhatt
  avatar: bio.jpg
  position: Assistant Professor & Faculty Fellow
  school: New York University
  place: #
  bio: "Faculty Fellow, New York University"
  email: umangbhatt@nyu.edu
  disqus-shortname:

  twitter: umangsbhatt #username
  facebook: #username
  google:
    plus: 
    analytics: G-JN7HSBS1PH
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  googlescholar: "https://scholar.google.com/citations?user=qq8bxPkAAAAJ&hl=en"
  github: umangsbhatt
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: umangsbhatt #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  scholar: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
